name: Build and Push Docker Image

on:
  push:
    branches:
      - mmaster

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t nagetto/ue19-lab-05:${{ github.sha }} .
          docker tag nagetto/ue19-lab-05:${{ github.sha }} nagetto/ue19-lab-05:latest

      - name: Push the Docker image to Docker Hub
        run: |
          docker push nagetto/ue19-lab-05:${{ github.sha }}
          docker push nagetto/ue19-lab-05:latest
